# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Sparkline Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	platform :ios, '13'

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../../'

end

target 'macOS Sparkline Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!
	platform :osx, '10.15'

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../../'

end

target 'macOS Sparkline Demo Objc' do
  # Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!

	platform :osx, '10.15'
  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../../'

end

target 'macOS Table Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!

	platform :osx, '10.15'

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../../'

end

target 'SwiftUI Sparkline Demo (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!

	platform :osx, '10.15'

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../../'

end

target 'SwiftUI Sparkline Demo (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!

	platform :ios, '13'

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../../'

end

target 'tvOS Sparkline Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!

	platform :tvos, '13'

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../../'

end
