# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'macOS Sparkline Demo' do
	platform :osx, '10.12'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../'
end

target 'macOS Sparkline Demo Objc' do
  platform :osx, '10.12'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../'
end

target 'macOS Table Demo' do
	platform :osx, '10.12'
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../'
end

target 'iOS Sparkline Demo' do
  platform :ios, '11.4'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../'
end

target 'tvOS Sparkline Demo' do
  platform :tvos, '11.4'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for macOS Sparkline Demo
  pod 'DSFSparkline', :path => '../'
end
